package org.example.sha1;

import static org.example.sha1.Sha1.encryptThisString;

public class Main {
    public static void main(String[] args) {

        System.out.println("HashCode Generated by SHA-1 for: ");

        String str1 = "ADA University";
        System.out.println("\n" + str1 + ": " + encryptThisString(str1));

        String str2 = "Hello, World!";
        System.out.println("\n" + str2 + ": " + encryptThisString(str2));
    }
}