package org.example.md5;

import java.security.NoSuchAlgorithmException;

import static org.example.md5.Md5.getMd5;

public class Main{
    public static void main(String[] args) {
        String s = "Div Academy";
        System.out.println(s);
        System.out.println("HashCode Generated by MD5: " + getMd5(s));

    }
}
